---
title: "Final Project"
author: "Ahsanul Choudhury"
date: "December 3, 2017"
output:
  html_document:
     theme: cerulean
     toc: true
     toc_float:
       collapsed: false
       smooth_scroll: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Load Libraries
```{r load_libraries, include=FALSE, cache=FALSE}
if (!require('readxl')) install.packages('readxl')
if (!require('httr')) install.packages('httr')
if (!require('dplyr')) install.packages('dplyr')
if (!require('reshape2')) install.packages('reshape2')
if (!require('RCurl')) install.packages('RCurl')
```

## 2016 Reported Hate Crime

Data was downloaded form each source, cleaned and uploded to github

### Map Data

Data source : https://ucr.fbi.gov/hate-crime/2016/tables/table-11

```{r load_data, echo=TRUE}
#Download and read data
url <- "https://github.com/choudhury1023/DATA-608/raw/master/Final_Project/table_11_offenses_offense_type_by_participating_state_2016.xls"
GET(url, write_disk("2016_data.xls", overwrite=TRUE))
df <- read_excel("2016_data.xls")

#Data Cleanup and manipulation

df <- df[-c(1:6, 57:60), ]
head(df)

df$code <- c("AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "DC", "FL", "GA", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY")
df1 <- df[ ,-c(3:17)]

colnames(df1) <- c("state","hate crimes", "code")

write.csv(df1, "df1.csv")

head(df1, 20)
```


### Pie Chart Data

```{r pie, echo=TRUE}
df2 <- df

ncol(df2)
colnames(df2) <- c("state","hate crimes","x1", "x2", "x3", "x4", "x5", "x6", "x7", "x8", "x9", "x10", "x11", "x12", "x13", "x14", "crimes against society" , "code")


df3 <- transform(df2,  x1 = as.numeric(x1),x2 = as.numeric(x2),x4 = as.numeric(x4),x5 = as.numeric(x5),x6 = as.numeric(x6),x7 = as.numeric(x7),
                 x8 = as.numeric(x8),x9 = as.numeric(x9),x10 = as.numeric(x10),x11 = as.numeric(x11),x12 = as.numeric(x12),x13 = as.numeric(x13),
                 x14 = as.numeric(x14)) 
               


df4 <-df3 %>% 
  replace(is.na(.), 0) %>%
  mutate(crimes.against.persons = x1 + x2 + x4 + x5 + x6 + x7)%>%
  mutate(crimes.against.property = x8 + x9 + x10 + x11 + x13 + x14)


df4 <- df4[,-c(2:16, 18)]

colnames(df4) <- c("state", "Crimes Against Society",  "Crimes Against Persons", "Crimes Against Property")


df5 <- melt(df4, id.vars=c("state"))
df5 <- df5[order(df5$state),] 


head(df5)

write.csv(df5, "2016_typef.csv")
```


## 2016 Population Data

Data Source: https://www.census.gov/data/datasets/2016/demo/popest/state-total.html

```{r population, echo=TRUE}
url <- c("https://github.com/choudhury1023/DATA-608/raw/master/Final_Project/nst-est2016-01.xlsx")
GET(url, write_disk("population.xlsx", overwrite=TRUE))
df6 <- read_excel("population.xlsx")

df6 <- df6[-c(1:8, 20, 60:67), ]
df6 <- df6[-c(2:9)]
colnames(df6) <- c("state","population")
head(df6)
tail(df6)
write.csv(df6, "pop.csv")
```


## Compare

2010-2015 Data source: https://github.com/fivethirtyeight/data/blob/master/hate-crimes/hate_crimes.csv

```{r compare, echo=TRUE}
raw <- getURL("https://raw.githubusercontent.com/choudhury1023/DATA-608/master/Final_Project/hate_crimes.csv")
df7 <- read.csv(text = raw)
df7 <- df7[-c(2:11)]
df7 <- df7[-c(12), ]

# combine 2016 hate crime data with population data and 2010-2016 data

df8 <- bind_cols(df1, df6, df7)
df8 <- df8[-c(4,6)]

sapply(df8, class)
colnames(df8) <- c("state", "hate_crimes", "code", "population", "avg_hatecrimes_per_100k_fbi_2010to2015")
df8$hate_crimes <- as.numeric(as.character(df8$hate_crimes))

# normalize 2016 data

df8$avg_hatecrimes_per_100k_fbi_2016 <- (df8$hate_crimes/df8$population)*100000

df8 <- df8[-c(2:4)]

df8$change <- df8$avg_hatecrimes_per_100k_fbi_2010to2015
df8$change[df8$avg_hatecrimes_per_100k_fbi_2010to2015 < df8$avg_hatecrimes_per_100k_fbi_2016] <- "States with Increased Hate Crimes in 2016"
df8$change[df8$avg_hatecrimes_per_100k_fbi_2010to2015 > df8$avg_hatecrimes_per_100k_fbi_2016] <- "States with Decreased Hate Crimes in 2016"

write.csv(df8, "compare.csv")

```
  
